# Generated by Django 4.1.7 on 2023-03-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0002_alter_tag_options_favorites_unique add to favorites'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorites',
            name='unique add to favorites',
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='рецепт уже есть в корзине'),
        ),
        migrations.AddConstraint(
            model_name='favorites',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='рецепт уже есть в избранном'),
        ),
    ]
